version: '3.7'
services:
  nginx:
    image: nginx
    volumes:
      - ~/new/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "3000:3000"
    command: sh -c "nginx -g 'daemon off;'"

  server_1:
    container_name: server_1
    build: ./server
    environment:
      - serverNum=1

  server_2:
    container_name: server_2
    build: ./server
    volumes:
      - ./server.js:/server.js
    environment:
      - serverNum=2

  server_3:
    container_name: server_3
    build: ./server
    volumes:
      - ./server.js:/server.js
    environment:
      - serverNum=3
