version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: sh -c "nginx -g 'daemon off;'"
  
  widget_one:
    container_name: widget_one
    image: nginx:alpine
    volumes:
      - ./widget_1/public:/usr/share/nginx/html
      - ./widget_1/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    command: sh -c "nginx -g 'daemon off;'"

  widget_two:
    container_name: widget_two
    image: nginx:alpine
    volumes:
      - ./widget_2/public:/usr/share/nginx/html
      - ./widget_2/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3001:80"
    command: sh -c "nginx -g 'daemon off;'"

  widget_three:
    container_name: widget_three
    image: nginx:alpine
    volumes:
      - ./widget_3/public:/usr/share/nginx/html
      - ./widget_3/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3002:80"
    command: sh -c "nginx -g 'daemon off;'"